
author:
    - name: Kannan Venkateswaran
      email: venkateswarkm@vcu.edu

date: 4/20/2024

format:
    html:
        theme: cosmo
        toc: true
        embed-resources: true
        code-copy: true

execute:
  echo: true
  eval: true
  cache: false
